function init_trust_page(display_element, trial) {
	let html = ''
    html += `
    <style>
        div {
            border: 0px solid #73AD21; 
        }
        div.veil {
            position: absolute;
            top: 0%;
            left: 0%;
            width: 100%;
            height: 100%;
            opacity: 100%;
            backdrop-filter: blur(50px);
            -webkit-backdrop-filter: blur(50px);
            display: none; 
        }
        h1.cross {
            position: absolute;
            top: 25%;
            left: 49%;
            font-size: 10vw;
        }
        div.wrap {
            position: absolute;
            top: 1vw;
            left: 1vw;
            width: 98vw;
            height: 48vw;
            border-radius: 40px;
            background-color: #f2f1f0;
        }
        div.banner {
        	position: absolute;
        	top: 0;
        	left: 0;
        	background-color: #f2f1f0;
        	width: 100%;
        	height: 10%;
        	border-radius: 40px 40px 0px 0px;
        }
		div.profile {
			position: absolute;
			border-color: #73AD21;
			border-width: 10px;
			top: 15%;
			left: 10%;
			height: 60%;
			width: 20%;
			border-radius: 40px;
			display: flex;
			justify-content: center;
			align-items: center;
			overflow: hidden;
		}
		img.profile {
			flex-shrink: 0;
			min-height: 100%;
			min-width: 100%;
			scale: 0.9;
		}
		div.bioBox {
			position: absolute;
			background-color: white;
			top: 15%;
			right: 10%;
			height: 77%;
			width: 50%;
			border-radius: 40px;
			box-shadow: inset 0 0 10px ;
			overflow: hidden;
		}
		div.bioText {
			position: absolute;
			top: 0.5%;
			left: 0;
			height: 93%;
			width: 96%;
			overflow-y: scroll;
			margin: 15px;
		}
		h1.profile {
			position: absolute;
			bottom: 5%;
			left: 17%;
			font-size: 4vw;
			color: #73AD21;
		}

		div.bannerButton {
			position: absolute;
			height: 100%;
			width: 25%;
			font-size: 2vw;
			text-align: center;
			font-weight: bold;
			padding-top: 20px;
			box-sizing: border-box;
		}
		div.npText {
			position: absolute;
			height: 10%;
			width: 15%;
			top: 17%;
			left: 25%;
			text-align: left;
			font-size: 2vw;
			font-weight: bold;
			opacity: 0%;
		}
		div.qText {
			position: absolute;
			height: 5%;
			width: 70%;
			top: 45%;
			left: 10%;
			text-align: left;
			font-size: 5vw;
			opacity: 0%;
		}
		div.choiceBox {
			position: absolute;
			bottom: 10%;
			height: 15%;
			width: 20%;
			font-size: 4vw;
			font-weight: bolder;
			padding-top: 2.5vw;
			box-sizing: border-box;
			border-radius: 20px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			opacity: 0%;
		}
		div.chatBox {
			position: absolute;
			top: 5%;
			right: 10%;
			height: 30%;
			width: 45%;
			font-size: 4vw;
			border-width: 10px;
			border-radius: 40px;
			font-size: 4vw;
			padding-top: 5vw;
			box-sizing: border-box;
			opacity: 0%;
		}
		div.fb_box {
            position: absolute;
            top: 20%;;
            left: 25%;
            width: 50%;
            height: 30%;
            border-radius: 40px;
            opacity: 0%;
            transition-timing-function: ease-in;
            font-size: 4vw;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }
		
        
    </style>
    <body>
        
    </body>
    `
    return html
}

function draw_trust_bio(display_element, trial) {
	const wrap = document.createElement('div')
	wrap.className = 'wrap'
	wrap.id = 'wrap'
	wrap.style.backgroundColor = get_bios(0).colorLight

	const veil = document.createElement('div')
	veil.className = 'veil'
	veil.id = 'veil'

	const banner = document.createElement('div')
	banner.className = 'banner'
	banner.id = 'banner'

	const pf_picc = document.createElement('div')
	pf_picc.className = 'profile'
	pf_picc.id = 'pf_pic'
	pf_picc.style.borderColor = get_bios(0).color
	const pf_pic = document.createElement('img')
	pf_pic.className = 'profile'
	pf_pic.src = 'img/pfpic.webp'

	const pf_name = document.createElement('h1')
	pf_name.className = 'profile'
	pf_name.id = 'pf_name'
	pf_name.style.color = get_bios(0).color
	pf_name.textContent = get_bios(0).name

	const bioBox = document.createElement('div')
	bioBox.className = 'bioBox'
	bioBox.id = 'bioBox'
	const bioText = document.createElement('div')
	bioText.className = 'bioText'
	bioText.id = 'bioText'
	bioText.textContent = get_bios(0).bio

	const startButton = document.createElement('div')
	startButton.className = 'bannerButton'
	startButton.id = 'startButton'
	startButton.style.right = '0%'
	startButton.style.borderRadius = '0px 40px 0px 0px'
	startButton.style.backgroundColor = '#de3a3a'
	startButton.textContent = 'Start Game'
	startButton.style.display = 'none'
	let ifclick = [1, 0, 0]
	for (let i = 1; i < 4; i++) {
		const x = document.createElement('div')
		x.className = 'bannerButton'
		x.id = `bB-${i}`
		x.style.left = `${(i-1) * 25}%`
		x.style.borderRadius = (i != 1)?'0px 0px 0px 0px':'40px 0px 0px 0px';
		x.style.backgroundColor = get_bios(i-1).colorLight
		x.textContent = get_bios(i-1).name
		x.onclick = function (e) {
			const x = (e.target.id.match(/\d+/)[0])-1
			document.getElementById('bioText').textContent = get_bios(x).bio
			document.getElementById('pf_name').textContent = get_bios(x).name
			document.getElementById('pf_name').style.color = get_bios(x).color
			document.getElementById('pf_pic').style.borderColor = get_bios(x).color
			document.getElementById('wrap').style.backgroundColor = get_bios(x).colorLight
			ifclick[x] = 1;
			if (ifclick.reduce((partialSum, a) => partialSum + a, 0) === 3) {
				document.getElementById('startButton').style.display = 'inline'
			}
		}
		banner.appendChild(x)
	}
	startButton.onclick = function () {
		console.log('GAME START')
		DrawTrustGame(display_element, trial)
	}
	pf_picc.appendChild(pf_pic)
	bioBox.appendChild(bioText)
	banner.appendChild(startButton)
	wrap.appendChild(banner)
	wrap.appendChild(pf_picc)
	wrap.appendChild(pf_name)
	wrap.appendChild(bioBox)
	display_element.appendChild(wrap)
	display_element.appendChild(veil)
	if (trial.displayBio === 0) {
		startButton.click()
	}



}

function get_bios(num) {
	let players = [
		{
			name: 'Jeff',
			color: '#94bf26',
			colorLight: '#cdd1b4',
			bio: `THIS IS A PLACE HOLDER FOR JEFF'S BIO. I FIRST STARTED TAKING CARE OF OTHER PEOPLE'S CHILDREN WHEN I WAS ACTUALLY STILL JUST A CHILD MYSELF SO THAT MEANT PEOPLE WERE PAYING ME BASICALLY TO PLAY AND THAT WAS REALLY AWESOME BUT IT ALSO MEANT THAT I WAS GETTING A TON OF CHILDCARE EXPERIENCE AND THAT BY THE TIME I WAS SIXTEEN I PROBABLY COULD MAKE MACARONI AND CHEESE WITH MY EYES SHUT OR CHANGE A DIAPER WITH ONE HAND TIED BEHIND MY BACK WHICH I ONLY PROBABLY EVER WOULD HAVE TO DO WITH THOSE VERY NAUGHTY NICHOLSON BOYS BUT UH THEIR MOTHER KNEW THEY WERE A HANDFUL SHE WAS PAYING TEN DOLLARS AN HOUR IN NINETEEN EIGHTY EIGHT SO I KIND OF THOUGHT THAT ALL OF MY CHILDCARE EXPERIENCE WAS GONNA TEACH ME EVERYTHING THAT I NEEDED TO KNOW ABOUT PARENTING MY OWN CHILDREN AND MY HUSBAND AND I WE HAD A DAUGHTER AND THEN A SON AND THEN WE DECIDED TO BECOME FOSTER PARENTS UH WITH THE INTENTION OF HOPEFULLY BEING ABLE TO ADOPT ONE DAY AND YOU KNOW HOW EVERYBODY ALWAYS SAYS YOU NEED A LICENSE TO DRIVE A CAR BUT YOU DON'T NEED ONE TO HAVE A CHILD THAT'S NOT TRUE WHEN YOU BECOME A FOSTER PARENT WE DID HAVE TO GET A LICENSE AND SO FIRST WE HAD TO TAKE THESE CLASSES WHERE THEY ASKED US REALLY HARD HITTING QUESTIONS LIKE IS SECONDHAND SMOKE GOOD OR BAD AND UM DO BABIES ACTUALLY NEED CAR SEATS AND THEN WE HAD TO DO UH ALL SORTS OF OTHER THINGS UM HAVE PHYSICALS DONE BACKGROUND CHECKS FINGERPRINTED HAVE OUR HOME INSPECTED INTERVIEWS I MEAN THE WHOLE THING TURNED OUT TO BE WAY MORE COMPLICATED THAN JUST CREATING A NEW HUMAN BEING WITH MY BODY AND THEN THERE WERE ALL THE QUESTIONS WHAT KIND OF CHILD WOULD WE BE WILLING TO TAKE A GIRL OR A BOY WHAT RACE WHAT AGE NOW I GREW UP WITH THREE SISTERS AND I ALREADY HAD ONE BOY THAT I DIDN'T ALWAYS KNOW HOW TO RELATE TO BUT THEN I HEARD THAT BOYS ARE ACTUALLY LEFT BEHIND MORE IN ADOPTION REQUESTS SO WE SAID THAT WE PREFERRED A BOY ANY RACE AND HAVING SURVIVED TWO INFANTS ALREADY WE THOUGHT THAT THAT PLEASURE COULD BE AFFORDED TO SOMEONE ELSE SO ANYTHING UP TO AGE FOUR THE AGE OF OUR BIOLOGICAL SON AT THE TIME AND WE GOT OUR LICENSE IN THE MAIL AND WE SETTLED IN FOR WHAT WE THOUGHT COULD BE A VERY LONG WAIT BUT WE GOT A PHONE CALL SIX WEEKS LATER ABOUT A BABY AT THE HOSPITAL AND I THOUGHT WOW AN INFANT DOESN'T EVERYBODY ELSE WANT AN INFANT BUT WE SAID YES AND WHEN WE WENT TO THE HOSPITAL TO PICK HIM UP THE NURSES INSISTED ON PUSHING ME OUT TO THE CAR IN A WHEELCHAIR WHICH I THOUGHT WAS VERY FUNNY I MEAN I DIDN'T SUFFER ANY PHYSICAL DISTRESS BRINGING THIS KID INTO THE WORLD AND EVEN THOUGH I THOUGHT IT WAS REALLY FUNNY THOUGH I REALIZED I WAS HAVING THE SAME EXACT OVERWHELMINGLY SURREAL SENSATION THAT I HAD WHEN I FIRST LEFT THE HOSPITAL WITH MY FIRST TWO BABIES AND THAT WAS THERE'S A NEW PERSON HERE THERE'S THIS NEW HUMAN BEING THAT'S SO TINY AND PERFECT AND AMAZING AND THIS HOSPITAL STAFF IS GONNA LET US JUST LEAVE WITH HIM EVEN THOUGH THEY LOOK REALLY CONFIDENT AND WE GOT HIM HOME AND IT BECAME OBVIOUS RIGHT AWAY THAT THERE WERE THINGS THAT WE STILL NEEDED TO LEARN IN SPITE OF YEARS OF BABYSITTING AND PARENTING EXPERIENCE AND HAVING A LICENSE TO PARENT LIKE WHAT TO DO WHEN A YOUNG WOMAN COMES BOUNCING UP TO YOU AND SAYS YOUR BABY IS SO CUTE IS HIS DADDY BLACK SO I JUST UH PRETENDED I COULDN'T REALLY REMEMBER OR WHAT TO DO WHEN A WOMAN TAPS YOU ON THE SHOULDER AT A CROWDED RESTAURANT AND DEMANDS TO KNOW WHERE'S THAT BABY FROM AND WHEN TOLD NEW JERSEY UH JUST CONTINUES TO KEEP ASKING BUT WHERE BEFORE THAT BUT WHERE BEFORE THAT UNTIL YOU'RE FINALLY JUST FORCED TO SAY A UTERUS OR WHAT TO DO WHEN YOUR FOUR YEAR OLD WHITE SON COMES RUNNING UP AND SAYS WE'RE PLAYING CIRCUS AND THE BABY HAS TO BE THE MONKEY BECAUSE HE'S BROWN AND YOUR AFRICAN AMERICAN CASE WORKER IS VISITING AND ALL YOU CAN THINK TO DO IS THAT YOU JUST WANNA DIE ON THE SPOT AND SO INSTEAD YOU JUST PRETEND YOU DIDN'T HEAR HIM AND MAKE A STRONG MENTAL NOTE TO TALK TO HIM ABOUT THAT LATER I DON'T THINK THEY TOLD US ANYTHING ABOUT TRANSRACIAL ADOPTION IN THOSE CLASSES UH THE MOST THEY MIGHT HAVE SAID WAS SOMETHING ALONG THE LINES OF IF YOU ARE WHITE AND HAVE A BLACK CHILD PLACED WITH YOU PLEASE FOR THE LOVE OF GOD GET SOME HELP WITH THEIR SKIN AND HAIR AND SO I TURNED TO MY BLACK FRIENDS AND AND I ASKED FOR HELP AND THEY HELPED ME AND THEY ALSO TAUGHT ME THINGS LIKE THAT MY LITTLE BLACK BOY WAS ONLY GONNA BE CUTE IN THE EYES OF THE PUBLIC FOR A CERTAIN AGE AND THEN HE WOULD UM SOMEHOW OVER NIGHT BE PERCEIVED AS THREATENING TO THE PUBLIC AND THAT IT WAS GONNA HAPPEN MUCH SOONER THAN I WOULD ANTICIPATE AND I LISTENED TO THEM AND I LEARNED FROM THEM BUT I DIDN'T EXPERIENCE ANY OF THAT HARSH REALITY YET AND OUR CASE MOVED ALONG AND WE WERE GIVEN THE GO AHEAD TO ADOPT HIM AND I GOT SOME PAPERWORK IN THE MAIL IT WAS AN ADOPTION SUBSIDY AGREEMENT AND NEXT TO THE NAME OF OUR ADORABLE FUNNY VERY LOVED AND VERY WANTED SON WAS THE REASON FOR THE MONTHLY SUBSIDY THAT HE WAS GONNA GET AH AND IT WAS CHECKED OFF CHILD IS HARD TO PLACE AFRICAN AMERICAN AND I FELT LIKE I HAD BEEN PUNCHED IN THE STOMACH AND THEN ONE DAY WE GET A PHONE CALL FROM OUR CASE WORKER AND I WASN'T EXPECTING IT AND I COULD TELL SOMETHING WAS UP AND I WAS RIGHT BECAUSE SHE SAID DO YOU HAVE ROOM FOR ANOTHER BABY AND WE WEREN'T REALLY PLANNING ON HAVING ANY MORE CHILDREN BUT UM WE LOVED OUR LITTLE SON SO MUCH WE LOVED ANY SIBLING OF HIS AND SO I SAID WHAT IS IT AND SHE SAID A BOY AND SO I CRIED A LITTLE WHEN I SAID OKAY AND THEN I SAID I GUESS I BETTER CALL MY HUSBAND AND ASK HIM REAL QUICK THOUGH SO THEN WE WERE UP TO FOUR CHILDREN ONE GIRL AND THREE BOYS AND I WAS PRETTY SURE THAT I WAS DONE WITH BABIES BUT THEN I WENT TO A BABY SHOWER AND ALL THE THE NEW MOM WAS OPENING UP ALL THESE TINY LITTLE SOCKS AND REALLY CUTE ONESIES AND THINGS AND ALL THE WOMEN WERE JUST GUSHING AND I REALIZE THAT I WAS SITTING LIKE A LITTLE BIT AWAY FROM THE REST OF THEM AND JUST THINKING THAT LOOKS LIKE MORE LAUNDRY TO ME SO THEN I REALLY KNEW THAT I WAS DONE WITH BABIES UNTIL I GOT A PHONE CALL ABOUT OUR BOY'S BABY SISTER AND COULD WE COME GET HER LIKE TODAY DID WE HAVE A CAR SEAT AND SO EVEN THOUGH WE KNEW IT MEANT GETTING ON ANOTHER TWO YEAR EMOTIONAL ROLLER COASTER WE BORROWED A CAR SEAT AND SAID YES SIX YEARS AFTER STARTING OUR FOSTERING EXPERIENCE WE HAD ADOPTED EACH OF OUR CHILDREN WE GOT TO SAY GOODBYE TO THE JUDGES AND THE CASE WORKERS AND GOOD RIDDANCE TO THE ONE THAT WE REFERRED TO AS THE ANTI SOCIAL WORKER AND HELLO TO THE ARCHITECT AND CONTRACTORS LESSONS WERE STILL BEING LEARNED AND MISTAKES WERE BEING MADE I CAN ADMIT THAT I HAVE BEEN THAT WHITE MOM OUT AT THE STORE WHEN A BLACK WOMAN TOLD ME THAT MY BABY'S HAIR FELT A LITTLE BIT DRY AND I KNEW I I HAD TO LEARN FROM ALL THESE DIFFERENT SOURCES THE THE BLACK COMMUNITY ADULT ADOPTEEST MORE EXPERIENCED TRANSRACIALLY ADOPTIVE FAMILIES AND ALL WHILE TRYING TO BALANCE IT WITH WHAT IT MEANT TO BE OUR FAMILY IN THIS TIME AND IN THIS PLACE AND I THOUGHT WE WERE DOING ALRIGHT AND THEN ONE DAY MY SON WAS GETTING READY FOR SCHOOL HE WAS SIX YEARS OLD AND UH GETTING READY FOR FIRST GRADE AND HE WAS BRUSHING HIS TEETH AND HE JUST STOPPED AND HE SAID I WISH A BROWN FAMILY ADOPTED ME HE HE WASN'T UPSET HE WAS VERY MATTER OF FACT LIKE I WANNA WEAR MY BLUE SNEAKERS AND I WISH A BROWN FAMILY ADOPTED ME BUT I WAS STUNNED I KNEW HE MIGHT SAY SOMETHING LIKE THAT AT SOME POINT BUT I JUST WASN'T REALLY EXPECTING IT AND SO I UH JUST TRIED TO STAY CALM AND I SAID OH WELL HOW COME AND HE SAID I WANT THE FAMILY TO LOOK LIKE ME AND SO I POINTED OUT THAT HIS YOUNGER BROTHER AND SISTER LOOKED LIKE HIM AND HE SAID YEAH BUT NOT THE WHOLE FAMILY AND SO I JUST APOLOGIZED I DIDN'T KNOW WHAT ELSE I COULD POSSIBLY DO AND I GOT HIM OFF TO SCHOOL AND THE WHOLE DAY I WAS THINKING YOU KNOW WHAT AM I GONNA DO ABOUT THIS AND ON ONE HAND I DIDN'T WANNA DO ANYTHING I MEAN THE KID SEEMS FINE I DON'T WANNA BOTHER HIM YOU KNOW GET HIM UPSET ABOUT IT BUT ON THE OTHER HAND YOU KNOW YOU HAVE TO MUDDLE THINGS UP SOMETIMES BEFORE YOU GET SOME CLARITY SO AT BEDTIME THAT NIGHT I MUDDLED THINGS UP AND I ASKED HIM ARE YOU STILL FEELING SAD THAT A BROWN FAMILY DIDN'T ADOPT YOU AND HE DIDN'T SAY ANYTHING HE JUST NODDED YES SO I SAID UM DID ANYBODY DO ANYTHING OR SAY SOMETHING RECENTLY THAT MADE YOU START TO FEEL THAT WAY AND AGAIN HE JUST NODDED NO SO NOW I'M GRASPING FOR STRAWS UM DID YOU KNOW THAT DADDY AND I LOVE YOU VERY VERY VERY VERY VERY MUCH AND AGAIN JUST A NOD YES I MEAN CLEARLY THE KID WAS NOT GONNA HELP ME MOVE THE CONVERSATION FORWARD AT ALL AND SO I I HAD NO IDEA WHAT TO SAY AND SO I ABSOLUTELY SURPRISED MYSELF WITH WHAT CAME OUT NEXT AND I SAID TO HIM DID YOU KNOW THAT THERE'S SADNESS TO ADOPTION AND THIS TIME HIS INTEREST WAS PIQUED BECAUSE THIS TIME HE SPOKE AND HE SAID NO I DIDN'T AND I SAID WELL YEAH MOST OF THE TIME EVERYBODY ONLY TALKS ABOUT HOW REALLY HAPPY ADOPTION IS AND WE ARE SO SO HAPPY THAT YOU'RE PART OF OUR FAMILY BUT IF THE WORLD WAS PERFECT AND THERE WERE NEVER ANY PROBLEMS AT ALL YOU PROBABLY COULD HAVE JUST STAYED WITH YOUR FIRST MOMMY DON'T YOU THINK AND THIS TIME MY BOY ANSWERED ME IT WASN'T WITH A NOD OR WITH WORDS BUT HE SOBBED IT WASN'T CRYING OVER A SKINNED KNEE HE WAS SOBBING OVER AN EMOTIONAL WOUND THAT HE DIDN'T KNOW HE HAD AND HE STILL LACKED THE EMOTIONAL MATURITY AND THE LANGUAGE TO REALLY EXPLORE IT BUT THERE WAS SOMETHING ABOUT MY ACKNOWLEDGING IT FOR HIM THAT JUST UNLOCKED THE DEEPEST SOB I'D EVER HEARD COME OUT OF A LITTLE CHILD AND I TOLD HIM IT WAS OKAY TO BE SAD ABOUT THAT AND MAYBE EVEN FOREVER BUT THAT I WANTED TO HELP HIM FIND PEACE OVER IT AND WOULD HE MAYBE LIKE TO TRY TO MEET SOME MORE OF HIS BIRTH FAMILY AND HE SAID YES SO I REACHED OUT TO OUR LAST CASE WORKER AND I I SAID I'D HEARD ABOUT THIS GREAT GRANDMA CAN YOU GIVE ME HER NUMBER OR SOMETHING AND HE SAID NO UM I'M ACTUALLY NOT ALLOWED TO GIVE THAT OUT SO I DID A LITTLE MORE ASKING AROUND AND SOME RESEARCH AND I FOUND OUT THAT HE COULD HOWEVER SEND A LETTER ON MY BEHALF NOW BASED ON MY HISTORY WITH THE STATE I DIDN'T REALLY TRUST THAT THIS WAS GONNA HAPPEN BUT I HAD TO TAKE A CHANCE I WROTE THE LETTER AND I SENT IT AND HOPED FOR THE BEST AND UH IT WORKED BECAUSE SHE CALLED US A WEEK OR TWO LATER THIS GREAT GRANDMOTHER WHO HAD WORRIED ABOUT THEM AND PRAYED FOR THEM FOR YEARS AND WE WENT TO GO MEET HER IMMEDIATELY AND AS SOON AS WE DID ALL THESE DOORS KEPT OPENING BECAUSE EVERY TIME WE WENT WE JUST WOULD MEET A NEW FAMILY MEMBER AND EACH ONE OF THEM WELCOMED ALL OF US OUR ADOPTED KIDS OUR BIOLOGICAL KIDS MY HUSBAND AND MYSELF WITH OPEN ARMS AND ALL THESE RELATIONSHIPS THAT COULD HAVE FELT AWKWARD OR STRAINED JUST NEVER DID AND OUR CHILDREN THRIVED BECAUSE OF IT AND THAT WAS FOUR YEARS AGO AND ON A MORE RECENT VISIT I WAS SITTING CA CATCHING UP WITH THE KIDS' AUNTIE LIKE ON A COUCH OVER HERE AND I COULD SEE MY HUSBAND EATING AND TALKING WITH ANOTHER FAMILY MEMBER OVER THERE AND SOME OF MY KIDS WERE DOING CRAFTS WITH SOME COUSINS AND OTHERS WERE RUNNING AROUND PLAYING NINJA TURTLES WITH OTHER COUSINS AND THERE WAS POPOP SITTING ON THE COUCH AND HE HAD THE TV ON THE NATURE CHANNEL WAY TOO LOUD LIKE HE ALWAYS HAS IT AND I KNOW THAT NOW AND THERE WAS MY SON JUST SNUGGLED UP BY HIS SIDE AND TRADING WILD ANIMAL FACTS WITH HIS GRANDFATHER AND LOOKING AROUND THE ROOM THAT DAY I THOUGHT TO MYSELF YOU KNOW GROWING UP I ALWAYS THOUGHT THAT ADOPTION JUST MEANT UH A NEW FAMILY FOR THE CHILDREN THAT ARE ADOPTED BUT LOOKING AROUND HERE I KNOW THAT IN OUR CASE IT MEANS SO MUCH MORE BECAUSE IT UH IT'S A FAMILY FOR ALL OF US sp`,
		},
		{
			name: 'Matt',
			color: '#66bbcc',
			colorLight: '#c8d8db',
			bio: `THIS IS A PLACE HOLDER FOR Matt'S BIO. E WHOLE THING TURNED OUT TO BE WAY MORE COMPLICATED THAN JUST CREATING A NEW HUMAN BEING WITH MY BODY AND THEN THERE WERE ALL THE QUESTIONS WHAT KIND OF CHILD WOULD WE BE WILLING TO TAKE A GIRL OR A BOY WHAT RACE WHAT AGE NOW I GREW UP WITH THREE SISTERS AND I ALREADY HAD ONE BOY THAT I DIDN'T ALWAYS KNOW HOW TO RELATE TO BUT THEN I HEARD THAT BOYS ARE ACTUALLY LEFT BEHIND MORE IN ADOPTION REQUESTS SO WE SAID THAT WE PREFERRED A BOY ANY RACE AND HAVING SURVIVED TWO INFANTS ALREADY WE THOUGHT THAT THAT PLEASURE COULD BE AFFORDED TO SOMEONE ELSE SO ANYTHING UP TO AGE FOUR THE AGE OF OUR BIOLOGICAL SON AT THE TIME AND WE GOT OUR LICENSE IN THE MAIL AND WE SETTLED IN FOR WHAT WE THOUGHT COULD BE A VERY LONG WAIT BUT WE GOT A PHONE CALL SIX WEEKS LATER ABOUT A BABY AT THE HOSPITAL AND I THOUGHT WOW AN INFANT DOESN'T EVERYBODY ELSE WANT AN INFANT BUT WE SAID YES AND WHEN WE WENT TO THE HOSPITAL TO PICK HIM UP THE NURSES INSISTED ON PUSHING ME OUT TO THE CAR IN A WHEELCHAIR WHICH I THOUGHT WAS VERY FUNNY I MEAN I DIDN'T SUFFER ANY PHYSICAL DISTRESS BRINGING THIS KID INTO THE WORLD AND EVEN THOUGH I THOUGHT IT WAS REALLY FUNNY THOUGH I REALIZED I WAS HAVING THE SAME EXACT OVERWHELMINGLY SURREAL SENSATION THAT I HAD WHEN I FIRST LEFT THE HOSPITAL WITH MY FIRST TWO BABIES AND THAT WAS THERE'S A NEW PERSON HERE THERE'S THIS NEW HUMAN BEING THAT'S SO TINY AND PERFECT AND AMAZING AND THIS HOSPITAL STAFF IS GONNA LET US JUST LEAVE WITH HIM EVEN THOUGH THEY LOOK REALLY CONFIDENT AND WE GOT HIM HOME AND IT BECAME OBVIOUS RIGHT AWAY THAT THERE WERE THINGS THAT WE STILL NEEDED TO LEARN IN SPITE OF YEARS OF BABYSITTING AND PARENTING EXPERIENCE AND HAVING A LICENSE TO PARENT LIKE WHAT TO DO WHEN A YOUNG WOMAN COMES BOUNCING UP TO YOU AND SAYS YOUR BABY IS SO CUTE IS HIS DADDY BLACK SO I JUST UH PRETENDED I COULDN'T REALLY REMEMBER OR WHAT TO DO WHEN A WOMAN TAPS YOU ON THE SHOULDER AT A CROWDED RESTAURANT AND DEMANDS TO KNOW WHERE'S THAT BABY FROM AND WHEN TOLD NEW JERSEY UH JUST CONTINUES TO KEEP ASKING BUT WHERE BEFORE THAT BUT WHERE BEFORE THAT UNTIL YOU'RE FINALLY JUST FORCED TO SAY A UTERUS OR WHAT TO DO WHEN YOUR FOUR YEAR OLD WHITE SON COMES RUNNING UP AND SAYS WE'RE PLAYING CIRCUS AND THE BABY HAS TO BE THE MONKEY BECAUSE HE'S BROWN AND YOUR AFRICAN AMERICAN CASE WORKER IS VISITING AND ALL YOU CAN THINK TO DO IS THAT YOU JUST WANNA DIE ON THE SPOT AND SO INSTEAD YOU JUST PRETEND YOU DIDN'T HEAR HIM AND MAKE A STRONG MENTAL NOTE TO TALK TO HIM ABOUT THAT LATER I DON'T THINK THEY TOLD US ANYTHING ABOUT TRANSRACIAL ADOPTION IN THOSE CLASSES UH THE MOST THEY MIGHT HAVE SAID WAS SOMETHING ALONG THE LINES OF IF YOU ARE WHITE AND HAVE A BLACK CHILD PLACED WITH YOU PLEASE FOR THE LOVE OF GOD GET SOME HELP WITH THEIR SKIN AND HAIR AND SO I TURNED TO MY BLACK FRIENDS AND AND I ASKED FOR HELP AND THEY HELPED ME AND THEY ALSO TAUGHT ME THINGS LIKE THAT MY LITTLE BLACK BOY WAS ONLY GONNA BE CUTE IN THE EYES OF THE PUBLIC FOR A CERTAIN AGE AND THEN HE WOULD UM SOMEHOW OVER NIGHT BE PERCEIVED AS THREATENING TO THE PUBLIC AND THAT IT WAS GONNA HAPPEN MUCH SOONER THAN I WOULD ANTICIPATE AND I LISTENED TO THEM AND I LEARNED FROM THEM BUT I DIDN'T EXPERIENCE ANY OF THAT HARSH REALITY YET AND OUR CASE MOVED ALONG AND WE WERE GIVEN THE GO AHEAD TO ADOPT HIM AND I GOT SOME PAPERWORK IN THE MAIL IT WAS AN ADOPTION SUBSIDY AGREEMENT AND NEXT TO THE NAME OF OUR ADORABLE FUNNY VERY LOVED AND VERY WANTED SON WAS THE REASON FOR THE MONTHLY SUBSIDY THAT HE WAS GONNA GET AH AND IT WAS CHECKED OFF CHILD IS HARD TO PLACE AFRICAN AMERICAN AND I FELT LIKE I HAD BEEN PUNCHED IN THE STOMACH AND THEN ONE DAY WE GET A PHONE CALL FROM OUR CASE WORKER AND I WASN'T EXPECTING IT AND I COULD TELL SOMETHING WAS UP AND I WAS RIGHT BECAUSE SHE SAID DO YOU HAVE ROOM FOR ANOTHER BABY AND WE WEREN'T REALLY PLANNING ON HAVING ANY MORE CHILDREN BUT UM WE LOVED OUR LITTLE SON SO MUCH WE LOVED ANY SIBLING OF HIS AND SO I SAID WHAT IS IT AND SHE SAID A BOY AND SO I CRIED A LITTLE WHEN I SAID OKAY AND THEN I SAID I GUESS I BETTER CALL MY HUSBAND AND ASK HIM REAL QUICK THOUGH SO THEN WE WERE UP TO FOUR CHILDREN ONE GIRL AND THREE BOYS AND I WAS PRETTY SURE THAT I WAS DONE WITH BABIES BUT THEN I WENT TO A BABY SHOWER AND ALL THE THE NEW MOM WAS OPENING UP ALL THESE TINY LITTLE SOCKS AND REALLY CUTE ONESIES AND THINGS AND ALL THE WOMEN WERE JUST GUSHING AND I REALIZE THAT I WAS SITTING LIKE A LITTLE BIT AWAY FROM THE REST OF THEM AND JUST THINKING THAT LOOKS LIKE MORE LAUNDRY TO ME SO THEN I REALLY KNEW THAT I WAS DONE WITH BABIES UNTIL I GOT A PHONE CALL ABOUT OUR BOY'S BABY SISTER AND COULD WE COME GET HER LIKE TODAY DID WE HAVE A CAR SEAT AND SO EVEN THOUGH WE KNEW IT MEANT GETTING ON ANOTHER TWO YEAR EMOTIONAL ROLLER COASTER WE BORROWED A CAR SEAT AND SAID YES SIX YEARS AFTER STARTING OUR FOSTERING EXPERIENCE WE HAD ADOPTED EACH OF OUR CHILDREN WE GOT TO SAY GOODBYE TO THE JUDGES AND THE CASE WORKERS AND GOOD RIDDANCE TO THE ONE THAT WE REFERRED TO AS THE ANTI SOCIAL WORKER AND HELLO TO THE ARCHITECT AND CONTRACTORS LESSONS WERE STILL BEING LEARNED AND MISTAKES WERE BEING MADE I CAN ADMIT THAT I HAVE BEEN THAT WHITE MOM OUT AT THE STORE WHEN A BLACK WOMAN TOLD ME THAT MY BABY'S HAIR FELT A LITTLE BIT DRY AND I KNEW I I HAD TO LEARN FROM ALL THESE DIFFERENT SOURCES THE THE BLACK COMMUNITY ADULT ADOPTEEST MORE EXPERIENCED TRANSRACIALLY ADOPTIVE FAMILIES AND ALL WHILE TRYING TO BALANCE IT WITH WHAT IT MEANT TO BE OUR FAMILY IN THIS TIME AND IN THIS PLACE AND I THOUGHT WE WERE DOING ALRIGHT AND THEN ONE DAY MY SON WAS GETTING READY FOR SCHOOL HE WAS SIX YEARS OLD AND UH GETTING READY FOR FIRST GRADE AND HE WAS BRUSHING HIS TEETH AND HE JUST STOPPED AND HE SAID I WISH A BROWN FAMILY ADOPTED ME HE HE WASN'T UPSET HE WAS VERY MATTER OF FACT LIKE I WANNA WEAR MY BLUE SNEAKERS AND I WISH A BROWN FAMILY ADOPTED ME BUT I WAS STUNNED I KNEW HE MIGHT SAY SOMETHING LIKE THAT AT SOME POINT BUT I JUST WASN'T REALLY EXPECTING IT AND SO I UH JUST TRIED TO STAY CALM AND I SAID OH WELL HOW COME AND HE SAID I WANT THE FAMILY TO LOOK LIKE ME AND SO I POINTED OUT THAT HIS YOUNGER BROTHER AND SISTER LOOKED LIKE HIM AND HE SAID YEAH BUT NOT THE WHOLE FAMILY AND SO I JUST APOLOGIZED I DIDN'T KNOW WHAT ELSE I COULD POSSIBLY DO AND I GOT HIM OFF TO SCHOOL AND THE WHOLE DAY I WAS THINKING YOU KNOW WHAT AM I GONNA DO ABOUT THIS AND ON ONE HAND I DIDN'T WANNA DO ANYTHING I MEAN THE KID SEEMS FINE I DON'T WANNA BOTHER HIM YOU KNOW GET HIM UPSET ABOUT IT BUT ON THE OTHER HAND YOU KNOW YOU HAVE TO MUDDLE THINGS UP SOMETIMES BEFORE YOU GET SOME CLARITY SO AT BEDTIME THAT NIGHT I MUDDLED THINGS UP AND I ASKED HIM ARE YOU STILL FEELING SAD THAT A BROWN FAMILY DIDN'T ADOPT YOU AND HE DIDN'T SAY ANYTHING HE JUST NODDED YES SO I SAID UM DID ANYBODY DO ANYTHING OR SAY SOMETHING RECENTLY THAT MADE YOU START TO FEEL THAT WAY AND AGAIN HE JUST NODDED NO SO NOW I'M GRASPING FOR STRAWS UM DID YOU KNOW THAT DADDY AND I LOVE YOU VERY VERY VERY VERY VERY MUCH AND AGAIN JUST A NOD YES I MEAN CLEARLY THE KID WAS NOT GONNA HELP ME MOVE THE CONVERSATION FORWARD AT ALL AND SO I I HAD NO IDEA WHAT TO SAY AND SO I ABSOLUTELY SURPRISED MYSELF WITH WHAT CAME OUT NEXT AND I SAID TO HIM DID YOU KNOW THAT THERE'S SADNESS TO ADOPTION AND THIS TIME HIS INTEREST WAS PIQUED BECAUSE THIS TIME HE SPOKE AND HE SAID NO I DIDN'T AND I SAID WELL YEAH MOST OF THE TIME EVERYBODY ONLY TALKS ABOUT HOW REALLY HAPPY ADOPTION IS AND WE ARE SO SO HAPPY THAT YOU'RE PART OF OUR FAMILY BUT IF THE WORLD WAS PERFECT AND THERE WERE NEVER ANY PROBLEMS AT ALL YOU PROBABLY COULD HAVE JUST STAYED WITH YOUR FIRST MOMMY DON'T YOU THINK AND THIS TIME MY BOY ANSWERED ME IT WASN'T WITH A NOD OR WITH WORDS BUT HE SOBBED IT WASN'T CRYING OVER A SKINNED KNEE HE WAS SOBBING OVER AN EMOTIONAL WOUND THAT HE DIDN'T KNOW HE HAD AND HE STILL LACKED THE EMOTIONAL MATURITY AND THE LANGUAGE TO REALLY EXPLORE IT BUT THERE WAS SOMETHING ABOUT MY ACKNOWLEDGING IT FOR HIM THAT JUST UNLOCKED THE DEEPEST SOB I'D EVER HEARD COME OUT OF A LITTLE CHILD AND I TOLD HIM IT WAS OKAY TO BE SAD ABOUT THAT AND MAYBE EVEN FOREVER BUT THAT I WANTED TO HELP HIM FIND PEACE OVER IT AND WOULD HE MAYBE LIKE TO TRY TO MEET SOME MORE OF HIS BIRTH FAMILY AND HE SAID YES SO I REACHED OUT TO OUR LAST CASE WORKER AND I I SAID I'D HEARD ABOUT THIS GREAT GRANDMA CAN YOU GIVE ME HER NUMBER OR SOMETHING AND HE SAID NO UM I'M ACTUALLY NOT ALLOWED TO GIVE THAT OUT SO I DID A LITTLE MORE ASKING AROUND AND SOME RESEARCH AND I FOUND OUT THAT HE COULD HOWEVER SEND A LETTER ON MY BEHALF NOW BASED ON MY HISTORY WITH THE STATE I DIDN'T REALLY TRUST THAT THIS WAS GONNA HAPPEN BUT I HAD TO TAKE A CHANCE I WROTE THE LETTER AND I SENT IT AND HOPED FOR THE BEST AND UH IT WORKED BECAUSE SHE CALLED US A WEEK OR TWO LATER THIS GREAT GRANDMOTHER WHO HAD WORRIED ABOUT THEM AND PRAYED FOR THEM FOR YEARS AND WE WENT TO GO MEET HER IMMEDIATELY AND AS SOON AS WE DID ALL THESE DOORS KEPT OPENING BECAUSE EVERY TIME WE WENT WE JUST WOULD MEET A NEW FAMILY MEMBER AND EACH ONE OF THEM WELCOMED ALL OF US OUR ADOPTED KIDS OUR BIOLOGICAL KIDS MY HUSBAND AND MYSELF WITH OPEN ARMS AND ALL THESE RELATIONSHIPS THAT COULD HAVE FELT AWKWARD OR STRAINED JUST NEVER DID AND OUR CHILDREN THRIVED BECAUSE OF IT AND THAT WAS FOUR YEARS AGO AND ON A MORE RECENT VISIT I WAS SITTING CA CATCHING UP WITH THE KIDS' AUNTIE LIKE ON A COUCH OVER HERE AND I COULD SEE MY HUSBAND EATING AND TALKING WITH ANOTHER FAMILY MEMBER OVER THERE AND SOME OF MY KIDS WERE DOING CRAFTS WITH SOME COUSINS AND OTHERS WERE RUNNING AROUND PLAYING NINJA TURTLES WITH OTHER COUSINS AND THERE WAS POPOP SITTING ON THE COUCH AND HE HAD THE TV ON THE NATURE CHANNEL WAY TOO LOUD LIKE HE ALWAYS HAS IT AND I KNOW THAT NOW AND THERE WAS MY SON JUST SNUGGLED UP BY HIS SIDE AND TRADING WILD ANIMAL FACTS WITH HIS GRANDFATHER AND LOOKING AROUND THE ROOM THAT DAY I THOUGHT TO MYSELF YOU KNOW GROWING UP I ALWAYS THOUGHT THAT ADOPTION JUST MEANT UH A NEW FAMILY FOR THE CHILDREN THAT ARE ADOPTED BUT LOOKING AROUND HERE I KNOW THAT IN OUR CASE IT MEANS SO MUCH MORE BECAUSE IT UH IT'S A FAMILY FOR ALL OF US sp`,

		},
		{
			name: 'Alex',
			color: '#4a26bf',
			colorLight: '#bab5c9',
			bio: `THIS IS A PLACE HOLDER FOR Alex'S BIO.  NICHOLSON BOYS BUT UH THEIR MOTHER KNEW THEY WERE A HANDFUL SHE WAS PAYING TEN DOLLARS AN HOUR IN NINETEEN EIGHTY EIGHT SO I KIND OF THOUGHT THAT ALL OF MY CHILDCARE EXPERIENCE WAS GONNA TEACH ME EVERYTHING THAT I NEEDED TO KNOW ABOUT PARENTING MY OWN CHILDREN AND MY HUSBAND AND I WE HAD A DAUGHTER AND THEN A SON AND THEN WE DECIDED TO BECOME FOSTER PARENTS UH WITH THE INTENTION OF HOPEFULLY BEING ABLE TO ADOPT ONE DAY AND YOU KNOW HOW EVERYBODY ALWAYS SAYS YOU NEED A LICENSE TO DRIVE A CAR BUT YOU DON'T NEED ONE TO HAVE A CHILD THAT'S NOT TRUE WHEN YOU BECOME A FOSTER PARENT WE DID HAVE TO GET A LICENSE AND SO FIRST WE HAD TO TAKE THESE CLASSES WHERE THEY ASKED US REALLY HARD HITTING QUESTIONS LIKE IS SECONDHAND SMOKE GOOD OR BAD AND UM DO BABIES ACTUALLY NEED CAR SEATS AND THEN WE HAD TO DO UH ALL SORTS OF OTHER THINGS UM HAVE PHYSICALS DONE BACKGROUND CHECKS FINGERPRINTED HAVE OUR HOME INSPECTED INTERVIEWS I MEAN THE WHOLE THING TURNED OUT TO BE WAY MORE COMPLICATED THAN JUST CREATING A NEW HUMAN BEING WITH MY BODY AND THEN THERE WERE ALL THE QUESTIONS WHAT KIND OF CHILD WOULD WE BE WILLING TO TAKE A GIRL OR A BOY WHAT RACE WHAT AGE NOW I GREW UP WITH THREE SISTERS AND I ALREADY HAD ONE BOY THAT I DIDN'T ALWAYS KNOW HOW TO RELATE TO BUT THEN I HEARD THAT BOYS ARE ACTUALLY LEFT BEHIND MORE IN ADOPTION REQUESTS SO WE SAID THAT WE PREFERRED A BOY ANY RACE AND HAVING SURVIVED TWO INFANTS ALREADY WE THOUGHT THAT THAT PLEASURE COULD BE AFFORDED TO SOMEONE ELSE SO ANYTHING UP TO AGE FOUR THE AGE OF OUR BIOLOGICAL SON AT THE TIME AND WE GOT OUR LICENSE IN THE MAIL AND WE SETTLED IN FOR WHAT WE THOUGHT COULD BE A VERY LONG WAIT BUT WE GOT A PHONE CALL SIX WEEKS LATER ABOUT A BABY AT THE HOSPITAL AND I THOUGHT WOW AN INFANT DOESN'T EVERYBODY ELSE WANT AN INFANT BUT WE SAID YES AND WHEN WE WENT TO THE HOSPITAL TO PICK HIM UP THE NURSES INSISTED ON PUSHING ME OUT TO THE CAR IN A WHEELCHAIR WHICH I THOUGHT WAS VERY FUNNY I MEAN I DIDN'T SUFFER ANY PHYSICAL DISTRESS BRINGING THIS KID INTO THE WORLD AND EVEN THOUGH I THOUGHT IT WAS REALLY FUNNY THOUGH I REALIZED I WAS HAVING THE SAME EXACT OVERWHELMINGLY SURREAL SENSATION THAT I HAD WHEN I FIRST LEFT THE HOSPITAL WITH MY FIRST TWO BABIES AND THAT WAS THERE'S A NEW PERSON HERE THERE'S THIS NEW HUMAN BEING THAT'S SO TINY AND PERFECT AND AMAZING AND THIS HOSPITAL STAFF IS GONNA LET US JUST LEAVE WITH HIM EVEN THOUGH THEY LOOK REALLY CONFIDENT AND WE GOT HIM HOME AND IT BECAME OBVIOUS RIGHT AWAY THAT THERE WERE THINGS THAT WE STILL NEEDED TO LEARN IN SPITE OF YEARS OF BABYSITTING AND PARENTING EXPERIENCE AND HAVING A LICENSE TO PARENT LIKE WHAT TO DO WHEN A YOUNG WOMAN COMES BOUNCING UP TO YOU AND SAYS YOUR BABY IS SO CUTE IS HIS DADDY BLACK SO I JUST UH PRETENDED I COULDN'T REALLY REMEMBER OR WHAT TO DO WHEN A WOMAN TAPS YOU ON THE SHOULDER AT A CROWDED RESTAURANT AND DEMANDS TO KNOW WHERE'S THAT BABY FROM AND WHEN TOLD NEW JERSEY UH JUST CONTINUES TO KEEP ASKING BUT WHERE BEFORE THAT BUT WHERE BEFORE THAT UNTIL YOU'RE FINALLY JUST FORCED TO SAY A UTERUS OR WHAT TO DO WHEN YOUR FOUR YEAR OLD WHITE SON COMES RUNNING UP AND SAYS WE'RE PLAYING CIRCUS AND THE BABY HAS TO BE THE MONKEY BECAUSE HE'S BROWN AND YOUR AFRICAN AMERICAN CASE WORKER IS VISITING AND ALL YOU CAN THINK TO DO IS THAT YOU JUST WANNA DIE ON THE SPOT AND SO INSTEAD YOU JUST PRETEND YOU DIDN'T HEAR HIM AND MAKE A STRONG MENTAL NOTE TO TALK TO HIM ABOUT THAT LATER I DON'T THINK THEY TOLD US ANYTHING ABOUT TRANSRACIAL ADOPTION IN THOSE CLASSES UH THE MOST THEY MIGHT HAVE SAID WAS SOMETHING ALONG THE LINES OF IF YOU ARE WHITE AND HAVE A BLACK CHILD PLACED WITH YOU PLEASE FOR THE LOVE OF GOD GET SOME HELP WITH THEIR SKIN AND HAIR AND SO I TURNED TO MY BLACK FRIENDS AND AND I ASKED FOR HELP AND THEY HELPED ME AND THEY ALSO TAUGHT ME THINGS LIKE THAT MY LITTLE BLACK BOY WAS ONLY GONNA BE CUTE IN THE EYES OF THE PUBLIC FOR A CERTAIN AGE AND THEN HE WOULD UM SOMEHOW OVER NIGHT BE PERCEIVED AS THREATENING TO THE PUBLIC AND THAT IT WAS GONNA HAPPEN MUCH SOONER THAN I WOULD ANTICIPATE AND I LISTENED TO THEM AND I LEARNED FROM THEM BUT I DIDN'T EXPERIENCE ANY OF THAT HARSH REALITY YET AND OUR CASE MOVED ALONG AND WE WERE GIVEN THE GO AHEAD TO ADOPT HIM AND I GOT SOME PAPERWORK IN THE MAIL IT WAS AN ADOPTION SUBSIDY AGREEMENT AND NEXT TO THE NAME OF OUR ADORABLE FUNNY VERY LOVED AND VERY WANTED SON WAS THE REASON FOR THE MONTHLY SUBSIDY THAT HE WAS GONNA GET AH AND IT WAS CHECKED OFF CHILD IS HARD TO PLACE AFRICAN AMERICAN AND I FELT LIKE I HAD BEEN PUNCHED IN THE STOMACH AND THEN ONE DAY WE GET A PHONE CALL FROM OUR CASE WORKER AND I WASN'T EXPECTING IT AND I COULD TELL SOMETHING WAS UP AND I WAS RIGHT BECAUSE SHE SAID DO YOU HAVE ROOM FOR ANOTHER BABY AND WE WEREN'T REALLY PLANNING ON HAVING ANY MORE CHILDREN BUT UM WE LOVED OUR LITTLE SON SO MUCH WE LOVED ANY SIBLING OF HIS AND SO I SAID WHAT IS IT AND SHE SAID A BOY AND SO I CRIED A LITTLE WHEN I SAID OKAY AND THEN I SAID I GUESS I BETTER CALL MY HUSBAND AND ASK HIM REAL QUICK THOUGH SO THEN WE WERE UP TO FOUR CHILDREN ONE GIRL AND THREE BOYS AND I WAS PRETTY SURE THAT I WAS DONE WITH BABIES BUT THEN I WENT TO A BABY SHOWER AND ALL THE THE NEW MOM WAS OPENING UP ALL THESE TINY LITTLE SOCKS AND REALLY CUTE ONESIES AND THINGS AND ALL THE WOMEN WERE JUST GUSHING AND I REALIZE THAT I WAS SITTING LIKE A LITTLE BIT AWAY FROM THE REST OF THEM AND JUST THINKING THAT LOOKS LIKE MORE LAUNDRY TO ME SO THEN I REALLY KNEW THAT I WAS DONE WITH BABIES UNTIL I GOT A PHONE CALL ABOUT OUR BOY'S BABY SISTER AND COULD WE COME GET HER LIKE TODAY DID WE HAVE A CAR SEAT AND SO EVEN THOUGH WE KNEW IT MEANT GETTING ON ANOTHER TWO YEAR EMOTIONAL ROLLER COASTER WE BORROWED A CAR SEAT AND SAID YES SIX YEARS AFTER STARTING OUR FOSTERING EXPERIENCE WE HAD ADOPTED EACH OF OUR CHILDREN WE GOT TO SAY GOODBYE TO THE JUDGES AND THE CASE WORKERS AND GOOD RIDDANCE TO THE ONE THAT WE REFERRED TO AS THE ANTI SOCIAL WORKER AND HELLO TO THE ARCHITECT AND CONTRACTORS LESSONS WERE STILL BEING LEARNED AND MISTAKES WERE BEING MADE I CAN ADMIT THAT I HAVE BEEN THAT WHITE MOM OUT AT THE STORE WHEN A BLACK WOMAN TOLD ME THAT MY BABY'S HAIR FELT A LITTLE BIT DRY AND I KNEW I I HAD TO LEARN FROM ALL THESE DIFFERENT SOURCES THE THE BLACK COMMUNITY ADULT ADOPTEEST MORE EXPERIENCED TRANSRACIALLY ADOPTIVE FAMILIES AND ALL WHILE TRYING TO BALANCE IT WITH WHAT IT MEANT TO BE OUR FAMILY IN THIS TIME AND IN THIS PLACE AND I THOUGHT WE WERE DOING ALRIGHT AND THEN ONE DAY MY SON WAS GETTING READY FOR SCHOOL HE WAS SIX YEARS OLD AND UH GETTING READY FOR FIRST GRADE AND HE WAS BRUSHING HIS TEETH AND HE JUST STOPPED AND HE SAID I WISH A BROWN FAMILY ADOPTED ME HE HE WASN'T UPSET HE WAS VERY MATTER OF FACT LIKE I WANNA WEAR MY BLUE SNEAKERS AND I WISH A BROWN FAMILY ADOPTED ME BUT I WAS STUNNED I KNEW HE MIGHT SAY SOMETHING LIKE THAT AT SOME POINT BUT I JUST WASN'T REALLY EXPECTING IT AND SO I UH JUST TRIED TO STAY CALM AND I SAID OH WELL HOW COME AND HE SAID I WANT THE FAMILY TO LOOK LIKE ME AND SO I POINTED OUT THAT HIS YOUNGER BROTHER AND SISTER LOOKED LIKE HIM AND HE SAID YEAH BUT NOT THE WHOLE FAMILY AND SO I JUST APOLOGIZED I DIDN'T KNOW WHAT ELSE I COULD POSSIBLY DO AND I GOT HIM OFF TO SCHOOL AND THE WHOLE DAY I WAS THINKING YOU KNOW WHAT AM I GONNA DO ABOUT THIS AND ON ONE HAND I DIDN'T WANNA DO ANYTHING I MEAN THE KID SEEMS FINE I DON'T WANNA BOTHER HIM YOU KNOW GET HIM UPSET ABOUT IT BUT ON THE OTHER HAND YOU KNOW YOU HAVE TO MUDDLE THINGS UP SOMETIMES BEFORE YOU GET SOME CLARITY SO AT BEDTIME THAT NIGHT I MUDDLED THINGS UP AND I ASKED HIM ARE YOU STILL FEELING SAD THAT A BROWN FAMILY DIDN'T ADOPT YOU AND HE DIDN'T SAY ANYTHING HE JUST NODDED YES SO I SAID UM DID ANYBODY DO ANYTHING OR SAY SOMETHING RECENTLY THAT MADE YOU START TO FEEL THAT WAY AND AGAIN HE JUST NODDED NO SO NOW I'M GRASPING FOR STRAWS UM DID YOU KNOW THAT DADDY AND I LOVE YOU VERY VERY VERY VERY VERY MUCH AND AGAIN JUST A NOD YES I MEAN CLEARLY THE KID WAS NOT GONNA HELP ME MOVE THE CONVERSATION FORWARD AT ALL AND SO I I HAD NO IDEA WHAT TO SAY AND SO I ABSOLUTELY SURPRISED MYSELF WITH WHAT CAME OUT NEXT AND I SAID TO HIM DID YOU KNOW THAT THERE'S SADNESS TO ADOPTION AND THIS TIME HIS INTEREST WAS PIQUED BECAUSE THIS TIME HE SPOKE AND HE SAID NO I DIDN'T AND I SAID WELL YEAH MOST OF THE TIME EVERYBODY ONLY TALKS ABOUT HOW REALLY HAPPY ADOPTION IS AND WE ARE SO SO HAPPY THAT YOU'RE PART OF OUR FAMILY BUT IF THE WORLD WAS PERFECT AND THERE WERE NEVER ANY PROBLEMS AT ALL YOU PROBABLY COULD HAVE JUST STAYED WITH YOUR FIRST MOMMY DON'T YOU THINK AND THIS TIME MY BOY ANSWERED ME IT WASN'T WITH A NOD OR WITH WORDS BUT HE SOBBED IT WASN'T CRYING OVER A SKINNED KNEE HE WAS SOBBING OVER AN EMOTIONAL WOUND THAT HE DIDN'T KNOW HE HAD AND HE STILL LACKED THE EMOTIONAL MATURITY AND THE LANGUAGE TO REALLY EXPLORE IT BUT THERE WAS SOMETHING ABOUT MY ACKNOWLEDGING IT FOR HIM THAT JUST UNLOCKED THE DEEPEST SOB I'D EVER HEARD COME OUT OF A LITTLE CHILD AND I TOLD HIM IT WAS OKAY TO BE SAD ABOUT THAT AND MAYBE EVEN FOREVER BUT THAT I WANTED TO HELP HIM FIND PEACE OVER IT AND WOULD HE MAYBE LIKE TO TRY TO MEET SOME MORE OF HIS BIRTH FAMILY AND HE SAID YES SO I REACHED OUT TO OUR LAST CASE WORKER AND I I SAID I'D HEARD ABOUT THIS GREAT GRANDMA CAN YOU GIVE ME HER NUMBER OR SOMETHING AND HE SAID NO UM I'M ACTUALLY NOT ALLOWED TO GIVE THAT OUT SO I DID A LITTLE MORE ASKING AROUND AND SOME RESEARCH AND I FOUND OUT THAT HE COULD HOWEVER SEND A LETTER ON MY BEHALF NOW BASED ON MY HISTORY WITH THE STATE I DIDN'T REALLY TRUST THAT THIS WAS GONNA HAPPEN BUT I HAD TO TAKE A CHANCE I WROTE THE LETTER AND I SENT IT AND HOPED FOR THE BEST AND UH IT WORKED BECAUSE SHE CALLED US A WEEK OR TWO LATER THIS GREAT GRANDMOTHER WHO HAD WORRIED ABOUT THEM AND PRAYED FOR THEM FOR YEARS AND WE WENT TO GO MEET HER IMMEDIATELY AND AS SOON AS WE DID ALL THESE DOORS KEPT OPENING BECAUSE EVERY TIME WE WENT WE JUST WOULD MEET A NEW FAMILY MEMBER AND EACH ONE OF THEM WELCOMED ALL OF US OUR ADOPTED KIDS OUR BIOLOGICAL KIDS MY HUSBAND AND MYSELF WITH OPEN ARMS AND ALL THESE RELATIONSHIPS THAT COULD HAVE FELT AWKWARD OR STRAINED JUST NEVER DID AND OUR CHILDREN THRIVED BECAUSE OF IT AND THAT WAS FOUR YEARS AGO AND ON A MORE RECENT VISIT I WAS SITTING CA CATCHING UP WITH THE KIDS' AUNTIE LIKE ON A COUCH OVER HERE AND I COULD SEE MY HUSBAND EATING AND TALKING WITH ANOTHER FAMILY MEMBER OVER THERE AND SOME OF MY KIDS WERE DOING CRAFTS WITH SOME COUSINS AND OTHERS WERE RUNNING AROUND PLAYING NINJA TURTLES WITH OTHER COUSINS AND THERE WAS POPOP SITTING ON THE COUCH AND HE HAD THE TV ON THE NATURE CHANNEL WAY TOO LOUD LIKE HE ALWAYS HAS IT AND I KNOW THAT NOW AND THERE WAS MY SON JUST SNUGGLED UP BY HIS SIDE AND TRADING WILD ANIMAL FACTS WITH HIS GRANDFATHER AND LOOKING AROUND THE ROOM THAT DAY I THOUGHT TO MYSELF YOU KNOW GROWING UP I ALWAYS THOUGHT THAT ADOPTION JUST MEANT UH A NEW FAMILY FOR THE CHILDREN THAT ARE ADOPTED BUT LOOKING AROUND HERE I KNOW THAT IN OUR CASE IT MEANS SO MUCH MORE BECAUSE IT UH IT'S A FAMILY FOR ALL OF US sp`,

		},
	]
	if (typeof num != 'undefined') {
		return players[num]
	} else {
		return players
	}

}

function DrawTrustGame(display_element, trial) {
	// hide all the bio-element so when it's called, it will always start fresh
	document.getElementById(`bB-${trial.player + 1}`).click()
	document.getElementById('wrap').style.backgroundColor = '#f2f1f0'
	document.getElementById('banner').style.opacity = '0%'
	document.getElementById('bioBox').style.opacity = '0%'
	const ani1_para = {duration:700,iterations: 1,delay:0,fill: 'forwards'}
	const ani2_para = {duration:200,iterations: 1,delay:800,fill: 'forwards'}
	const pfpic = document.getElementById('pf_pic')
	pfpic.animate([
		{
			height: '60%', width: '20%', top: '15%', left: '10%',
		},{
			height: '30%', width: '12%', top: '5%', left: '10%',
		}],ani1_para)
	pfpic.firstElementChild.animate([
		{
			scale: '0.9',
		},{
			scale: '0.4',
		}],ani1_para)
	const pfname = document.getElementById('pf_name')
	pfname.animate([
		{
			left: '17%',  bottom: '5%',
		},{
			left: '25%', bottom: '58%',
		}],ani1_para)
	ani2_para.delay = 700
	const npText=document.createElement('div')
	npText.textContent = 'Now Playing With ...'
	npText.className = 'npText'
	npText.style.color = get_bios(trial.player).color
	document.getElementById('wrap').appendChild(npText)
	npText.animate([{opacity: '0%'},{opacity: '100%'}],ani1_para)

	const offerText = document.createElement('div')
	offerText.innerHTML = 'For <b>15</b> points'
	offerText.className = 'qText'
	offerText.id = 'offerText'
	document.getElementById('wrap').appendChild(offerText)
	offerText.animate([{opacity: '0%'},{opacity: '100%'}],ani2_para)

	const qText=document.createElement('div')
	qText.innerHTML = 'Would you <b>SHARE</b> or <b>KEEP</b>?'
	qText.className = 'qText'
	qText.id = 'qText'
	qText.style.top = '60%'
	document.getElementById('wrap').appendChild(qText)
	qText.animate([{opacity: '0%'},{opacity: '100%'}],ani2_para)

	const f_box = document.createElement('div')
	f_box.className = 'choiceBox'
	f_box.id = 'f_box'
	f_box.textContent = 'SHARE'
	f_box.style.left = '10%'
	f_box.style.backgroundColor = get_bios(trial.player).colorLight

	ani2_para.delay += 400
	const j_box = document.createElement('div')
	j_box.className = 'choiceBox'
	j_box.id = 'j_box'
	j_box.textContent = 'KEEP'
	j_box.style.right = '10%'
	j_box.style.backgroundColor = get_bios(trial.player).colorLight
	document.getElementById('wrap').appendChild(f_box)
	document.getElementById('wrap').appendChild(j_box)
	f_box.animate([{opacity: '0%'},{opacity: '100%'}],ani2_para)
	const opt_done = j_box.animate([{opacity: '0%'},{opacity: '100%'}],ani2_para).finished

	const chat_box = document.createElement('div')
	chat_box.className = 'chatBox'
	chat_box.id = 'chatBox'
	chat_box.style.backgroundColor = get_bios(trial.player).colorLight
	chat_box.style.borderColor = get_bios(trial.player).color
	chat_box.innerHTML = `${get_bios(trial.player).name} <b>Shared</b>!`
	document.getElementById('wrap').appendChild(chat_box)

	opt_done.then(() => {
		let keyboardListener = jsPsych.pluginAPI.getKeyboardResponse({
			callback_function: function (e) {
				drawTrustFeedback(e,display_element,trial)
			},
			valid_responses: ['j','J','f','F'],
			rt_method: 'performance',
			persist: false,
			allow_held_key: false
		});
	})

}

function drawTrustFeedback(e,display_element,trial) {
	const a1c = {duration:300,iterations: 1,delay:0,fill: 'forwards'}
	const a2c = {duration:300,iterations: 1,delay:0,fill: 'forwards'}
	const a3c = {duration:300,iterations: 1,delay:500,fill: 'forwards'}
	document.getElementById('qText').animate([{opacity: '100%'},{opacity: '0%'}],a1c)
	document.getElementById('offerText').animate([{opacity: '100%'},{opacity: '0%'}],a1c)
	const ani1 =document.getElementById(`${e.key}_box`).animate([{
		backgroundColor:get_bios(trial.player).colorLight, scale: '1',
	},{
		backgroundColor:get_bios(trial.player).color, scale: '1.3',
	}],{
		duration:300,iterations: 1,delay:0,fill: 'forwards'
	}).finished
	if (trial.share === 0) {
		document.getElementById('chatBox').style.backgroundColor = '#e0e0e0'
		document.getElementById('chatBox').style.borderColor = '#c0c1c2'
		document.getElementById('chatBox').innerHTML=`${get_bios(trial.player).name} <b>Kept</b>!`
	}
	ani1.then(() => {
		let ani2 = document.getElementById('chatBox').animate([{
			opacity: '0%', scale: '1'
		},{
			opacity: '100%', scale: '1.1'
		},{
			opacity: '100%', scale: '1'
		},{
			opacity: '100%', scale: '1.1'
		},{
			opacity: '100%', scale: '1.1'
		}],a2c).finished
		ani2.then(()=>{
			document.getElementById('veil').style.display = 'inline'
			document.getElementById('veil').style.backdropFilter = 'none'
			document.getElementById('veil').style.webkitBackdropFilter = 'none'
			document.getElementById('veil').animate([{
				backdropFilter: 'none',webkitBackdropFilter: 'none'
			},{
				backdropFilter: 'blur(20px)',webkitBackdropFilter: 'blur(20px)'
			}],a3c)
			const ptBox = document.createElement('div')
			ptBox.className = 'fb_box'
			if (e.key === 'f' && trial.share) {
				ptBox.style.backgroundColor = '#abbf99'
			} else {
				ptBox.style.backgroundColor = '#e0e0e0'
			}
			ptBox.textContent = 'You Got 30 points!'
			document.getElementById('veil').appendChild(ptBox)
			const pBani = ptBox.animate([{
				opacity: '0%'
			},{
				opacity: '100%'
			}],a3c).finished
			pBani.then(()=>{
				jsPsych.finishTrial()
			})
		})
	})

}